# Generated by Django 2.2.6 on 2019-11-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsCatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
