# Generated by Django 2.2.6 on 2019-11-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsCatch', '0002_accumulatedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulatedata',
            name='time',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='titledata',
            name='time',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
