# Generated by Django 2.2.1 on 2019-11-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsCatch', '0004_auto_20191112_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
